version: "3"
services:
  db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: groupomania
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306 
    volumes: 
      - /Users/mathildedescamps/www/groupomania/mysql:/var/lib/mysql
      - /Users/mathildedescamps/www/groupomania/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
    - groupomania
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment: 
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 8082:80
    networks:
      - groupomania
    depends_on: 
      - db
networks: 
  groupomania:
